# frozen_string_literal: true

# This file provides a reference for creating skills.
# Actual skills will be generated by the AI.

# Example skill structure:
#
# class MySkill < Fang::Skill
#   description "Brief description of what this skill does"
#
#   param :name, :string, required: true, description: "User name"
#   param :age, :integer, required: false, description: "User age"
#
#   def call(name:, age: nil)
#     # Implementation here
#     send_message("Hello, #{name}!")
#
#     # Return a result
#     { success: true, message: "Skill executed" }
#   end
# end

# Built-in helpers available in all skills:
# - send_message(content, conversation_id: nil)
# - schedule_task(title:, scheduled_for:, skill_name:, parameters:)
# - run_query(sql)
# - before_call, after_call, on_error hooks
